name: CLHPhotog
favicon: null
layout_spectrum: 0
typography_spectrum: 0.1562836
title: "Cody L Hall's Photography"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#CFFAFA'
    - '#6ED0E9'
    - '#D8CF90'
    - '#A2441E'
  brandStrength: 0.8254564
  lightness: 0.2808808
  saturation: 0.8995703
  rhythmicContrast: 0.8856068
purpose: []
